### ISSUE TITLE
Remove firmware blobs from src code and upload to releases

### ISSUE THREAD

**Issue by hmohiuddinTT** [tenstorrent/tt-firmware#1]
I noticed this repo has both the releases which have not been updated in a while and the blobs being uploaded straight to the src code (which are more up-to-date), I imagine as LFS blobs. Can we instead remove everything from source and release only via the GitHub releases feature. I think that would make things more consistent in terms of releases between the different repos.

**Comment by warthog9** [comment]
releases doesn't quite fit with how this repo works, so nuking the existing old release and we'll just pull things directly from the repo as we are expecting.
