### ISSUE TITLE
core temp abnormal

### ISSUE THREAD

**Issue by maychair** [tenstorrent/tt-firmware#4]
We installed 4 wormhole n150 cards on the server. Abnormal temperature caused tt-smi to crash. After re-flashing the firmware, 2 cards were successful, while 2 cards failed. Among them, the cards that successfully updated the firmware did not have temperature issues.

**Comment by warthog9** [comment]
If this wasn't resolved can you get us the output from tt-flash, and/or can you confirm you are using the latest tt-flash, and possibly the latest luwen from github?

**Comment by milank94** [comment]
@maychair can you provide any additional context as mentioned above? Is this issue still persistent?
