### ISSUE TITLE
Add a tag release for patched version

### ISSUE THREAD

**Issue by tapspatel** [tenstorrent/tt-firmware#5]
The patched bundle: fw_pack-80.8.11.0.fwbundle is not under any tagged release. We are creating automated scripts to checkout tags and build them, and need this bundle to be part of a tag.

**Comment by warthog9** [comment]
We aren't doing tags for the patches as we don't want to encourage normal user to use the patches.

**Comment by tapspatel** [comment]
Thanks @warthog9 I'll workaround this.
