### ISSUE TITLE
Release 80.8.12 after SW teams have verified patch on their infrastructure

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-firmware#6]
Metal is good with 80.8.12

Do we need sign off from Buda, or should we continue?

**Comment by tapspatel** [comment]
To add onto this, we will also need the equivalent 80.8.12 patch for galaxy.

**Comment by tapspatel** [comment]
Any updates?

**Comment by tapspatel** [comment]
hi, any updates?

**Comment by TTDRosen** [comment]
With the release of 80.10 (for both Galaxy and pcie cards) this should be resolved.
